# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Tweet Data Club"
description:        "Predicting @realDonaldTrump Tweet Patterns"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//tweetdata.club"
author:             "tweetdata.club"
twitter:
  username:         "tweetdata.club"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/
paid_site_link:    "https://tweetdataclub.github.io/site/"

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Subscribe"
    href:           "https://tweetdataclub.github.io/site/"
  - name:           "Buy Data"
    href:           "https://tweetdataclub.github.io/site/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
